### ISSUE TITLE
The git icon on the right side points to the wrong repo

### ISSUE THREAD

**Issue by yuval6957** [fastai/course22-web#8]
The fast.ai web site https://course.fast.ai/ was created from this repo ( https://github.com/fastai/course22-web)
But the github reference is to  https://github.com/fastai/course22 which is misleading. 
The error is in _quarto.yml:
`repo-url: https://github.com/fastai/course22`
should be changed to 
`repo-url: https://github.com/fastai/course22-web`

and this change should also be done for the navbar

**Comment by jph00** [comment]
Thanks - fixed now.
